/**
 * Envelope-name login matching.
 *
 * Guests read their name off the envelope their invitation arrived in, which is
 * a *household* addressee line ("Samuel & Margaux Gross"), not the Notion
 * `Full Name` the login endpoint has always required. This module resolves such
 * a string to a household and, where possible, to the specific people named.
 *
 * The envelope strings themselves were generated by this repo — see
 * `formatEnvelopeName()` in scripts/generate-invitation-csv.mjs — then
 * hand-corrected before printing, and imported back into the Notion Guest List
 * `Envelope Names` property by scripts/import-envelope-names.mjs.
 *
 * Two independent rules produce a match; see `matchHousehold`.
 *
 * Everything here is pure: no Notion, no I/O, no config. The Notion-side
 * candidate retrieval lives in src/lib/notion.ts (`findHouseholdByEnvelopeName`).
 */

import type { GuestRecord } from '../types';
import { normalize } from './normalize';

/**
 * Honorifics dropped from both sides of a comparison.
 *
 * The Guest List carries a `Title` select (Mr./Mrs./Ms./Dr.) that the CSV
 * generator prepends to first names, but the printed envelopes did not
 * consistently use it. Stripping titles everywhere means "Mr. Samuel Gross" and
 * "Samuel Gross" behave identically no matter which form was printed or typed.
 *
 * `m` covers French "M." — `envelopeTokens` strips the period before comparing.
 */
const TITLES = new Set([
  'mr',
  'mrs',
  'ms',
  'mx',
  'dr',
  'm',
  'mme',
  'mlle',
  'monsieur',
  'madame',
  'mademoiselle',
]);

/** Joining words between names. "&" survives normalize() as its own token. */
const CONNECTORS = new Set(['and', 'et', '&', '+', 'plus']);

/**
 * Reduce a name to comparable tokens: normalize (lowercase, strip accents and
 * apostrophes, hyphens to spaces), then drop titles, connectors, and the " +1"
 * suffix the CSV generator appends for unnamed plus-ones.
 *
 * Collective words ("The", "Family", "Famille") are deliberately *kept*. They
 * only appear in hand-edited envelopes, where they carry meaning: stripping
 * them would reduce "The Gross Family" to "gross", letting a bare surname
 * unlock that household — surname-only matching we specifically don't want.
 * A stored envelope is printed text and is compared as printed.
 *
 * Returns tokens in input order; callers that compare whole names should treat
 * the result as a set, since envelope word order varies.
 */
export function envelopeTokens(input: string): string[] {
  return normalize(input)
    // "+1" / "+ 1" anywhere — normalize() leaves the plus attached to the digit
    .replace(/\+\s*1\b/g, ' ')
    // Periods: normalize() keeps them, so "Mr." would never match the title
    // list, and an initial "J." should compare as "j".
    .replace(/\./g, '')
    .split(/\s+/)
    .filter(Boolean)
    .filter((token) => !TITLES.has(token))
    .filter((token) => !CONNECTORS.has(token));
}

/**
 * Group guests into households by connected component over the `Related Guests`
 * self-relation.
 *
 * Union-find, not a single hop: `getGuestParty()` in src/lib/notion.ts walks one
 * level of relations, which misses a third member in a household wired A↔B, B↔C.
 * This mirrors `makeUF()` in scripts/generate-invitation-csv.mjs so the site
 * groups guests into exactly the households the envelopes were addressed to.
 */
export function buildHouseholds(guests: GuestRecord[]): GuestRecord[][] {
  const parent = new Map<string, string>();
  for (const guest of guests) parent.set(guest.id, guest.id);

  const find = (id: string): string => {
    let root = id;
    while (parent.get(root) !== root) root = parent.get(root)!;
    // Path compression
    let cursor = id;
    while (parent.get(cursor) !== root) {
      const next = parent.get(cursor)!;
      parent.set(cursor, root);
      cursor = next;
    }
    return root;
  };

  const union = (a: string, b: string): void => {
    const rootA = find(a);
    const rootB = find(b);
    if (rootA !== rootB) parent.set(rootA, rootB);
  };

  for (const guest of guests) {
    for (const relatedId of guest.relatedGuestIds) {
      // Skip relations pointing outside this set (partial candidate fetches)
      if (parent.has(relatedId)) union(guest.id, relatedId);
    }
  }

  const households = new Map<string, GuestRecord[]>();
  for (const guest of guests) {
    const root = find(guest.id);
    const existing = households.get(root);
    if (existing) existing.push(guest);
    else households.set(root, [guest]);
  }

  return [...households.values()];
}

/** Normalized first name of a guest, or '' when Notion has no First Name. */
function firstNameToken(guest: GuestRecord): string {
  return guest.firstName ? normalize(guest.firstName) : '';
}

/** Normalized last-name tokens — a surname may itself be multi-word ("Van Dyke"). */
function lastNameTokens(guest: GuestRecord): string[] {
  return guest.lastName ? normalize(guest.lastName).split(/\s+/).filter(Boolean) : [];
}

/**
 * Rule (a): the input matches one of the household's stored envelope strings.
 *
 * Compared as token *sets* so word order and connector style don't matter — the
 * printed "Samuel & Margaux Gross" also accepts "Margaux Samuel Gross". A stored
 * envelope names the household, not a person, so callers disambiguate across the
 * whole household.
 */
function matchesStoredEnvelope(inputTokens: string[], members: GuestRecord[]): boolean {
  const inputKey = [...inputTokens].sort().join(' ');
  if (!inputKey) return false;

  for (const member of members) {
    for (const envelope of member.envelopeNames ?? []) {
      const storedKey = [...envelopeTokens(envelope)].sort().join(' ');
      if (storedKey && storedKey === inputKey) return true;
    }
  }
  return false;
}

/**
 * Rule (b): every input token is a first name or a surname somewhere in this
 * household, at least one is a first name, and no two input tokens claim the
 * same member.
 *
 * Accepts "Samuel Gross", "Samuel & Margaux Gross", "Margaux and Samuel Gross",
 * and "Margaux Gross" (Margaux's surname is Ancel, but Gross is a household
 * surname). Rejects "Gross" alone — a bare surname names nobody — and anything
 * containing a token this household doesn't own.
 *
 * Returns the IDs of the members whose first names appeared, or null.
 */
function matchesFirstNameCombination(
  inputTokens: string[],
  members: GuestRecord[]
): string[] | null {
  if (inputTokens.length === 0) return null;

  const householdSurnames = new Set(members.flatMap(lastNameTokens));

  // First name → members sharing it. Two people in one household with the same
  // first name is vanishingly rare, but the map keeps the assignment honest.
  const byFirstName = new Map<string, GuestRecord[]>();
  for (const member of members) {
    const token = firstNameToken(member);
    if (!token) continue;
    const existing = byFirstName.get(token);
    if (existing) existing.push(member);
    else byFirstName.set(token, [member]);
  }

  const claimed = new Set<string>();

  for (const token of inputTokens) {
    const candidates = byFirstName.get(token);
    if (candidates) {
      // Assign this token to a member who hasn't already been named
      const available = candidates.find((member) => !claimed.has(member.id));
      if (!available) return null; // e.g. "Samuel Samuel Gross"
      claimed.add(available.id);
      continue;
    }

    // Not a first name — must then be a surname this household owns
    if (!householdSurnames.has(token)) return null;
  }

  if (claimed.size === 0) return null; // surname only, names nobody
  return [...claimed];
}

/**
 * Resolve a typed name against one household.
 *
 * Returns the member IDs the name identifies, or null if it doesn't match.
 * A stored-envelope match returns the whole household (the string names no one
 * in particular); a first-name match returns only the people actually named.
 *
 * Callers log the guest straight in when exactly one member comes back, and
 * show the identity picker otherwise.
 */
export function matchHousehold(
  input: string,
  members: GuestRecord[]
): { memberIds: string[] } | null {
  const inputTokens = envelopeTokens(input);
  if (inputTokens.length === 0 || members.length === 0) return null;

  const named = matchesFirstNameCombination(inputTokens, members);
  if (named) return { memberIds: named };

  if (matchesStoredEnvelope(inputTokens, members)) {
    return { memberIds: members.map((member) => member.id) };
  }

  return null;
}

/**
 * Run `matchHousehold` across every household in a guest list.
 *
 * Returns the single matching household's member IDs, or null when nothing
 * matches *or* when more than one household matches. Ambiguity fails closed: it
 * should not happen with real data, and guessing would risk signing someone into
 * a stranger's RSVP. An ambiguous hit is surfaced to the caller via `onAmbiguous`
 * so it can be logged and investigated.
 */
export function findMatchingHousehold(
  input: string,
  guests: GuestRecord[],
  onAmbiguous?: (matches: string[][]) => void
): string[] | null {
  const matches: string[][] = [];

  for (const household of buildHouseholds(guests)) {
    const match = matchHousehold(input, household);
    if (match) matches.push(match.memberIds);
  }

  if (matches.length === 1) return matches[0];
  if (matches.length > 1) onAmbiguous?.(matches);
  return null;
}
