/**
 * Envelope-name login matching.
 *
 * Guests read their name off the envelope their invitation arrived in, which is
 * a *household* addressee line ("Samuel & Margaux Gross"), not the Notion
 * `Full Name` the login endpoint has always required. This module resolves such
 * a string to a household and, where possible, to the specific people named.
 *
 * The envelope strings themselves were generated by this repo — see
 * `formatEnvelopeName()` in scripts/generate-invitation-csv.mjs — then
 * hand-corrected before printing, and imported back into the Notion Guest List
 * `Envelope Names` property by scripts/import-envelope-names.mjs.
 *
 * Two independent rules produce a match; see `matchHousehold`.
 *
 * Both rules need a surname: a household is never unlocked by given names alone,
 * however those given names were derived. An alternate name widens *which* token
 * satisfies the given-name half, never whether the surname half is needed.
 *
 * The rules also absorb the ways a guest's everyday name differs from the one
 * Notion holds, since this is the layer that runs once exact matching misses:
 *
 *  - a **space-free multi-word surname** ("LeGuezec" for "Le Guezec"), derived,
 *    no data entry;
 *  - **`Also Known As`** — hand-edited alternate given names and surnames on
 *    the Notion record (a maiden name, "Bitsy" for "Elizabeth"), which is the
 *    escape hatch for anything not derivable, and needs no deploy;
 *  - **initials** of a hyphenated given name, and **common diminutives** from
 *    src/lib/nicknames.ts.
 *
 * The last three narrow themselves back off whenever they would make two
 * members of one household ambiguous — see `nameForms`.
 *
 * Everything here is pure: no Notion, no I/O, no config. The Notion-side
 * candidate retrieval lives in src/lib/notion.ts (`findHouseholdByEnvelopeName`).
 */

import type { GuestRecord } from '../types';
import { normalize } from './normalize';
import { nameVariants, deriveInitials } from './nicknames';

/**
 * Honorifics dropped from both sides of a comparison.
 *
 * The Guest List carries a `Title` select (Mr./Mrs./Ms./Dr.) that the CSV
 * generator prepends to first names, but the printed envelopes did not
 * consistently use it. Stripping titles everywhere means "Mr. Samuel Gross" and
 * "Samuel Gross" behave identically no matter which form was printed or typed.
 *
 * `m` covers French "M." — `envelopeTokens` strips the period before comparing.
 */
const TITLES = new Set([
  'mr',
  'mrs',
  'ms',
  'mx',
  'dr',
  'm',
  'mme',
  'mlle',
  'monsieur',
  'madame',
  'mademoiselle',
]);

/** Joining words between names. "&" survives normalize() as its own token. */
const CONNECTORS = new Set(['and', 'et', '&', '+', 'plus']);

/**
 * Reduce a name to comparable tokens: normalize (lowercase, strip accents and
 * apostrophes, hyphens to spaces), then drop titles, connectors, and the " +1"
 * suffix the CSV generator appends for unnamed plus-ones.
 *
 * Collective words ("The", "Family", "Famille") are deliberately *kept*. They
 * only appear in hand-edited envelopes, where they carry meaning: stripping
 * them would reduce "The Gross Family" to "gross", letting a bare surname
 * unlock that household — surname-only matching we specifically don't want.
 * A stored envelope is printed text and is compared as printed.
 *
 * Returns tokens in input order; callers that compare whole names should treat
 * the result as a set, since envelope word order varies.
 */
export function envelopeTokens(input: string): string[] {
  return normalize(input)
    // "+1" / "+ 1" anywhere — normalize() leaves the plus attached to the digit
    .replace(/\+\s*1\b/g, ' ')
    // Periods: normalize() keeps them, so "Mr." would never match the title
    // list, and an initial "J." should compare as "j".
    .replace(/\./g, '')
    .split(/\s+/)
    .filter(Boolean)
    .filter((token) => !TITLES.has(token))
    .filter((token) => !CONNECTORS.has(token));
}

/**
 * Group guests into households by connected component over the `Related Guests`
 * self-relation.
 *
 * Union-find, not a single hop: `getGuestParty()` in src/lib/notion.ts walks one
 * level of relations, which misses a third member in a household wired A↔B, B↔C.
 * This mirrors `makeUF()` in scripts/generate-invitation-csv.mjs so the site
 * groups guests into exactly the households the envelopes were addressed to.
 */
export function buildHouseholds(guests: GuestRecord[]): GuestRecord[][] {
  const parent = new Map<string, string>();
  for (const guest of guests) parent.set(guest.id, guest.id);

  const find = (id: string): string => {
    let root = id;
    while (parent.get(root) !== root) root = parent.get(root)!;
    // Path compression
    let cursor = id;
    while (parent.get(cursor) !== root) {
      const next = parent.get(cursor)!;
      parent.set(cursor, root);
      cursor = next;
    }
    return root;
  };

  const union = (a: string, b: string): void => {
    const rootA = find(a);
    const rootB = find(b);
    if (rootA !== rootB) parent.set(rootA, rootB);
  };

  for (const guest of guests) {
    for (const relatedId of guest.relatedGuestIds) {
      // Skip relations pointing outside this set (partial candidate fetches)
      if (parent.has(relatedId)) union(guest.id, relatedId);
    }
  }

  const households = new Map<string, GuestRecord[]>();
  for (const guest of guests) {
    const root = find(guest.id);
    const existing = households.get(root);
    if (existing) existing.push(guest);
    else households.set(root, [guest]);
  }

  return [...households.values()];
}

/**
 * First-name tokens. Multi-token on purpose: hyphenated and two-word given
 * names are common in the real guest list, and normalize() turns hyphens into
 * spaces, so a single-string comparison could never match the tokens a guest
 * types.
 *
 * Tokenized with `envelopeTokens`, the same function the *typed* name goes
 * through, so the two sides can never disagree about what a token is. That
 * matters for the unnamed plus-ones recorded with a literal `First Name` of
 * "<name> +1": the typed side always has its " +1" stripped, so a stored side
 * that kept it could never be claimed, and the whole household fell back to
 * needing its envelope line verbatim.
 */
function firstNameTokens(guest: GuestRecord): string[] {
  return guest.firstName ? envelopeTokens(guest.firstName) : [];
}

/** Normalized last-name tokens — a surname may itself be multi-word ("Van Dyke"). */
function lastNameTokens(guest: GuestRecord): string[] {
  return guest.lastName ? normalize(guest.lastName).split(/\s+/).filter(Boolean) : [];
}

/**
 * Split a guest's `Also Known As` lines into the alternate names they add.
 *
 * Each line is read the way a name is read everywhere else in this repo (see
 * the `submitRSVP` name write-back): **the last whitespace-delimited token is a
 * surname, the tokens before it are a given name**. A single-token line is a
 * given name only, since a bare surname must never unlock a household.
 *
 *   "PJ"              → given name "pj"
 *   "Bitsy"           → given name "bitsy"
 *   "Camille Garnier" → given name "camille", surname "garnier"
 *
 * Surnames join the *household's* pool rather than the individual's, matching
 * how `matchesFirstNameCombination` already treats a partner's surname — which
 * is what makes "Camille Garnier", "Camille Muller" and "Camille Garnier
 * Muller" all resolve from the single line above.
 */
function akaParts(guest: GuestRecord): { givenNames: string[][]; surnames: string[] } {
  const givenNames: string[][] = [];
  const surnames: string[] = [];

  for (const line of guest.aka ?? []) {
    const tokens = envelopeTokens(line);
    if (tokens.length === 0) continue;
    if (tokens.length === 1) {
      givenNames.push(tokens);
      continue;
    }
    surnames.push(tokens[tokens.length - 1]);
    givenNames.push(tokens.slice(0, -1));
  }

  return { givenNames, surnames };
}

/**
 * Every surname token this household answers to.
 *
 * Beyond the literal tokens of each member's `Last Name`, this adds:
 *
 *  - the **space-free** form of a multi-word surname ("Le Guezec" → "leguezec"),
 *    so a guest who types their surname closed up is not locked out. The
 *    opposite direction — stored closed up, typed spaced — is handled by the
 *    greedy join in `remainingAreSurnames`, so both spellings work whichever
 *    way round Notion happens to hold them;
 *  - surnames contributed by `Also Known As` (a maiden or married name).
 */
function householdSurnames(members: GuestRecord[]): Set<string> {
  const surnames = new Set<string>();

  for (const member of members) {
    const tokens = lastNameTokens(member);
    for (const token of tokens) surnames.add(token);
    if (tokens.length > 1) surnames.add(tokens.join(''));
    for (const surname of akaParts(member).surnames) surnames.add(surname);
  }

  return surnames;
}

/**
 * Are all leftover tokens surnames of this household?
 *
 * Walks left to right, and where a token isn't a surname on its own, tries
 * joining it with the tokens that follow — so a household stored as
 * "LeGuezec" still accepts someone typing "Le Guezec".
 */
function remainingAreSurnames(remaining: string[], surnames: Set<string>): boolean {
  let index = 0;

  while (index < remaining.length) {
    if (surnames.has(remaining[index])) {
      index += 1;
      continue;
    }

    let joined = remaining[index];
    let matchedAt = -1;
    for (let next = index + 1; next < remaining.length; next += 1) {
      joined += remaining[next];
      if (surnames.has(joined)) {
        matchedAt = next;
        break;
      }
    }

    if (matchedAt === -1) return false;
    index = matchedAt + 1;
  }

  return true;
}

/**
 * One way a member can be addressed, as an ordered list of token positions.
 * Each position holds every token accepted there, so "Mike" and "Michael" can
 * both satisfy the same slot without the caller knowing which was stored.
 */
interface NameForm {
  member: GuestRecord;
  /** The stored tokens, used only for longest-first ordering. */
  tokens: string[];
  accepted: ReadonlySet<string>[];
}

/**
 * Build the name forms a household answers to.
 *
 * `variants` turns on the common-diminutive table, `extras` turns on the forms
 * that don't come from `First Name` — `Also Known As` given names and derived
 * initials. Both are switched off tier by tier by `nameForms` when they would
 * make two members of one household ambiguous.
 */
function buildNameForms(
  members: GuestRecord[],
  { variants, extras }: { variants: boolean; extras: boolean }
): NameForm[] {
  const accept = (tokens: string[]): ReadonlySet<string>[] =>
    tokens.map((token) => (variants ? nameVariants(token) : new Set([token])));

  const forms: NameForm[] = [];

  for (const member of members) {
    const given = firstNameTokens(member);
    if (given.length > 0) forms.push({ member, tokens: given, accepted: accept(given) });

    if (!extras) continue;

    const initials = deriveInitials(given);
    if (initials) {
      forms.push({ member, tokens: [initials], accepted: [new Set([initials])] });
    }

    for (const alias of akaParts(member).givenNames) {
      forms.push({ member, tokens: alias, accepted: accept(alias) });
    }
  }

  // Longest first, so a two-token "Mary Anne" is consumed whole rather than
  // being shadowed by a "Mary" elsewhere in the household.
  return forms.sort((a, b) => b.tokens.length - a.tokens.length);
}

/**
 * Would these forms let one typed token name two different people?
 *
 * Members who genuinely share a first name are exempt: a named guest and an
 * unnamed +1 recorded under the same first name both being claimed is correct,
 * and is how the household already behaves. What this catches is ambiguity
 * *introduced* by widening — an Alex and an Alexander under one roof, where
 * "Alex" would otherwise claim whichever record happened to sort first.
 */
function formsAreAmbiguous(forms: NameForm[], members: GuestRecord[]): boolean {
  const literalFirst = new Map(
    members.map((member) => [member.id, firstNameTokens(member).join(' ')])
  );

  const accepts = new Map<string, Set<string>>();
  for (const form of forms) {
    const existing = accepts.get(form.member.id) ?? new Set<string>();
    for (const position of form.accepted) for (const token of position) existing.add(token);
    accepts.set(form.member.id, existing);
  }

  const entries = [...accepts.entries()];
  for (let i = 0; i < entries.length; i += 1) {
    for (let j = i + 1; j < entries.length; j += 1) {
      const [idA, acceptsA] = entries[i];
      const [idB, acceptsB] = entries[j];
      if (literalFirst.get(idA) === literalFirst.get(idB)) continue;
      for (const token of acceptsA) if (acceptsB.has(token)) return true;
    }
  }

  return false;
}

/**
 * The widest set of name forms that stays unambiguous for this household.
 *
 * Tiers narrow rather than disable: a household containing both an Alex and an
 * Alexander loses the diminutive table but keeps its `Also Known As` entries,
 * and only a household whose *stored* alternate names collide falls all the way
 * back to plain `First Name` matching — the behaviour before any of this
 * existed. Narrowing is always safe, because every tier is a subset of the one
 * above it.
 */
function nameForms(members: GuestRecord[]): NameForm[] {
  const tiers = [
    { variants: true, extras: true },
    { variants: false, extras: true },
    { variants: false, extras: false },
  ];

  for (const tier of tiers) {
    const forms = buildNameForms(members, tier);
    if (!formsAreAmbiguous(forms, members)) return forms;
  }

  // Even plain `First Name` matching can be ambiguous — a household holding
  // both a "Jean" and a "Jean-Pierre" always was. Returning it anyway keeps
  // that household behaving exactly as it did before, rather than inventing a
  // new failure for it.
  return buildNameForms(members, { variants: false, extras: false });
}

/**
 * Rule (a): the input matches one of the household's stored envelope strings.
 *
 * Compared as token *sets* so word order and connector style don't matter — the
 * printed "Samuel & Margaux Gross" also accepts "Margaux Samuel Gross". A stored
 * envelope names the household, not a person, so callers disambiguate across the
 * whole household.
 *
 * A second comparison joins the tokens in *input order* with no separator, so a
 * multi-word surname typed closed up ("The LeGuezec Family") still matches the
 * printed line. That one is order-sensitive by necessity — removing the spaces
 * is only meaningful while the words are still adjacent — but an envelope
 * copied off the invitation is normally typed in the order it was printed.
 */
function matchesStoredEnvelope(inputTokens: string[], members: GuestRecord[]): boolean {
  const inputKey = [...inputTokens].sort().join(' ');
  if (!inputKey) return false;
  const inputSpaceless = inputTokens.join('');

  for (const member of members) {
    for (const envelope of member.envelopeNames ?? []) {
      const storedTokens = envelopeTokens(envelope);
      if (storedTokens.length === 0) continue;
      if ([...storedTokens].sort().join(' ') === inputKey) return true;
      if (storedTokens.join('') === inputSpaceless) return true;
    }
  }
  return false;
}

/**
 * Rule (b): every input token is a given name or a surname somewhere in this
 * household, at least one is a given name, **at least one is a surname**, and no
 * two input tokens claim the same member.
 *
 * Accepts "Samuel Gross", "Samuel & Margaux Gross", "Margaux and Samuel Gross",
 * and "Margaux Gross" (Margaux's surname is Ancel, but Gross is a household
 * surname). Rejects "Gross" alone — a bare surname names nobody — and anything
 * containing a token this household doesn't own.
 *
 * It also rejects a given name standing alone ("Samuel", "Samuel & Margaux").
 * This rule was always documented as first names *plus a household surname*, but
 * until now it accepted the given names by themselves, which made a login as
 * weak as a first name: on the real list every household was reachable that way,
 * 183 lone given names logged straight in, and 49 more opened an identity picker
 * spanning up to six people — a guest typing a common first name could see
 * strangers' names and sign in as one of them.
 *
 * A household with no surname anywhere (its surname sits inside `First Name`)
 * therefore matches nothing here. That is intentional and costs it nothing:
 * exact `Full Name` matching runs first and still admits those guests.
 *
 * A "given name" here is whatever `nameForms` accepts for that member: their
 * `First Name`, plus — where it stays unambiguous within the household — their
 * `Also Known As` entries, their initials, and common diminutives.
 *
 * Returns the IDs of the members whose given names appeared, or null.
 */
function matchesFirstNameCombination(
  inputTokens: string[],
  members: GuestRecord[]
): string[] | null {
  if (inputTokens.length === 0) return null;

  const surnames = householdSurnames(members);
  const forms = nameForms(members);

  // Consume input tokens as a multiset: every position of a member's name must
  // be present, and no token may be spent twice.
  let remaining = [...inputTokens];
  const claimed = new Set<string>();

  for (const form of forms) {
    // A member already named by an earlier form must not consume more tokens
    if (claimed.has(form.member.id)) continue;

    const pool = [...remaining];
    let complete = true;

    for (const position of form.accepted) {
      const index = pool.findIndex((token) => position.has(token));
      if (index === -1) {
        complete = false;
        break;
      }
      pool.splice(index, 1);
    }

    if (complete) {
      remaining = pool;
      claimed.add(form.member.id);
    }
  }

  if (claimed.size === 0) return null; // surname only, or nobody named

  // A member whose given name is indistinguishable from a claimed member's must
  // be offered alongside them: the typed name genuinely does not say which one
  // it means, and consuming the token for whichever record happened to sort
  // first would sign the guest in as the wrong person without ever asking.
  //
  // This is the norm, not an edge case — an unnamed plus-one is recorded under
  // their host's given name ("<host> +1"), so every such household has two
  // members answering to it. Returning both sends it to the identity picker.
  const givenNameKey = (member: GuestRecord) => firstNameTokens(member).join(' ');
  const claimedKeys = new Set(
    members.filter((member) => claimed.has(member.id)).map(givenNameKey)
  );
  for (const member of members) {
    if (claimed.has(member.id)) continue;
    const key = givenNameKey(member);
    if (key && claimedKeys.has(key)) claimed.add(member.id);
  }

  // A surname is required, not merely permitted: with none left over, the guest
  // typed given names alone and the household is identified by a first name.
  if (remaining.length === 0) return null;

  // Whatever is left must be surnames this household owns. A leftover given
  // name means it was typed twice ("Samuel Samuel Gross") or belongs to
  // someone this household doesn't contain.
  if (!remainingAreSurnames(remaining, surnames)) return null;

  // Household order, not typed order, so the picker is stable across phrasings
  return members.filter((member) => claimed.has(member.id)).map((member) => member.id);
}

/**
 * Resolve a typed name against one household.
 *
 * Returns the member IDs the name identifies, or null if it doesn't match.
 * A stored-envelope match returns the whole household (the string names no one
 * in particular); a first-name match returns only the people actually named.
 *
 * Callers log the guest straight in when exactly one member comes back, and
 * show the identity picker otherwise.
 */
export function matchHousehold(
  input: string,
  members: GuestRecord[]
): { memberIds: string[] } | null {
  const inputTokens = envelopeTokens(input);
  if (inputTokens.length === 0 || members.length === 0) return null;

  const named = matchesFirstNameCombination(inputTokens, members);
  if (named) return { memberIds: named };

  if (matchesStoredEnvelope(inputTokens, members)) {
    return { memberIds: members.map((member) => member.id) };
  }

  return null;
}

/**
 * Run `matchHousehold` across every household in a guest list.
 *
 * Returns the member IDs the name identifies, or null when nothing matches.
 *
 * More than one household can legitimately match: an envelope is addressed to
 * the people who were invited together, but those people are deliberately split
 * into separate `Related Guests` groups when they should RSVP separately. The
 * printed line then names everyone while belonging to no single household, so
 * the matched households are unioned and the caller shows the identity picker
 * over all of them. Whichever person the guest picks decides which group — and
 * therefore which RSVP — they land on.
 *
 * That union is only safe while the candidates are **distinguishable to the
 * guest**, since the picker asks them to recognise their own name. If two
 * matched people share a display name, the guest cannot tell which is them and
 * could pick a stranger's record, so that case still fails closed and is
 * surfaced via `onAmbiguous` for investigation. (Two members of the *same*
 * household sharing a name is fine and unchanged: they are on one envelope at
 * one address, which is how an unnamed +1 is recorded.)
 */
export function findMatchingHousehold(
  input: string,
  guests: GuestRecord[],
  onAmbiguous?: (matches: string[][]) => void
): string[] | null {
  const matches: string[][] = [];

  for (const household of buildHouseholds(guests)) {
    const match = matchHousehold(input, household);
    if (match) matches.push(match.memberIds);
  }

  if (matches.length === 0) return null;
  if (matches.length === 1) return matches[0];

  const byId = new Map(guests.map((guest) => [guest.id, guest]));
  const unioned = matches.flat();

  // One display name may only stand for one person across the picker
  const seenNames = new Set<string>();
  for (const id of unioned) {
    const name = byId.get(id)?.normalizedName;
    if (!name) continue;
    if (seenNames.has(name)) {
      onAmbiguous?.(matches);
      return null;
    }
    seenNames.add(name);
  }

  return unioned;
}
